% txData = [0;1;0;0;0;1;0;0;0;0;0;0;0;0;1;0;0;0;0;0];
% rxData = rician(txData);

function rxData = rician(binary_data)
    txData = transpose(binary_data);
    ricianchan = comm.RicianChannel( ...
    'SampleRate',1e5, ...
    'PathDelays',[0.0 0.5 1.2]*1e-6, ...
    'AveragePathGains',[0.1 0.5 0.2], ...
    'KFactor',2.8, ...
    'DirectPathDopplerShift',5.0, ...
    'DirectPathInitialPhase',0.5, ...
    'MaximumDopplerShift',50, ...
    'DopplerSpectrum',doppler('Bell', 8), ...
    'RandomStream','mt19937ar with seed', ...
    'PathGainsOutputPort',true);
    data = pskmod(txData, 2);
    [chanout1,pg] = ricianchan(data);
    chaninfo = info(ricianchan);
    coeff = chaninfo.ChannelFilterCoefficients;
    Np = length(ricianchan.PathDelays);
    fracdelaydata = zeros(size(data,1),Np);
    for ii = 1:Np
        fracdelaydata(:,ii) = filter(coeff(ii,:),1,data);
    end
    chanout2 = sum(pg .* fracdelaydata,2);
    rxData = pskdemod(chanout2, 2);
    biterr(txData,rxData)
end
